### ISSUE TITLE
Update Nightscout REST API to v3

### ISSUE THREAD

**Issue by tolot27** [NightscoutFoundation/xDrip#1765]
As described in https://github.com/NightscoutFoundation/xDrip/issues/475#issuecomment-850774431, we should support the new Nightscout REST API to track changes and deletions better.

List of tasks to implement:
- [ ] determine Nightscout REST API version
- [ ] show API version in Nightscout Uploader and Follower status page
- [ ] create a new class for new API
- [ ] create a Factory class to instantiate the correct Nightscout communication class
- [ ] implement new commands like corrected sgv (#1090) or changed/deleted treatments (#1403)
- [ ] merge Uploader and Follower source code to avoid similar problems like #1807 addresses
- [ ] support uploading of activity
- [ ] support for the new Transmitter ID and Sensor Code fields (#1624)
- [ ] incorporate it into a sync framework

The requests which be used for the new REST API are described at [HTTP Methods](https://restfulapi.net/http-methods).

**Comment by tolot27** [comment]
@sulkaharo API v3 UPDATE does not support an eventType or note for svg entries. Does it matter?

Any further hints?

**Comment by tolot27** [comment]
The requests which be used for the new REST API are described at [HTTP Methods](https://restfulapi.net/http-methods)

**Comment by Icke12** [comment]
> As described in https://github.com/NightscoutFoundation/xDrip/issues/475#issuecomment-850774431, we should support the new Nightscout REST API to track changes and deletions better.
> 
> List of tasks to implement:
> - [ ] determine Nightscout REST API version
> - [ ] show API version in Nightscout Uploader and Follower status page
> - [ ] create a new class for new API
> - [ ] create a Factory class to instantiate the correct Nightscout communication class
> - [ ] implement new commands like corrected sgv (#1090) or changed/deleted treatments (#1403)
> - [ ] merge Uploader and Follower source code to avoid similar problems like #1807 addresses
> - [ ] support uploading of activity
> - [ ] support for the new Transmitter ID and Sensor Code fields (#1624)
> - [ ] incorporate it into a sync framework
> 
> The requests which be used for the new REST API are described at [HTTP Methods](https://restfulapi.net/http-methods).

**Comment by tolot27** [comment]
@Icke12 You just quoted my description. What do you want to say?

**Comment by Navid200** [comment]
@sulkaharo 
Would you please tell us what the need is for updating to V3?  
What do we lose if we don't update?
What do we gain if we update?

**Comment by Navid200** [comment]
I have been told the following two statements.
  
- xDrip does not delete or update any records.  Therefore, there is no need to change from V1 to V3.  
  
- Since AAPS 3.2, if AAPS uses xDrip as the CGM source, AAPS does all the uploading to Nightscout.  
  
Taking those into consideration, I am closing this issue.  Of course, we can reopen if needed.
